version: 2

project_name: migration-go

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: migration-go

    binary: migration-go

    main: .

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w
      - -X github.com/guverz/migration-go/cmd.version={{ .Version }}

archives:
  - id: default

    formats:
      - zip

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git

release:
  github:
    owner: guverz
    name: migration-go

scoops:
  - name: migration-go

    repository:
      owner: guverz
      name: scoop-bucket
      branch: main

    homepage: "https://github.com/guverz/migration-go"
    description: "CLI for managing database migration files across a Git repository and its Git submodules"
    license: MIT

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "chore(scoop): update migration-go to {{ .Tag }}"